#! /usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use GuzzleHttp\Client as Client;
use installer\NewInstaller;
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Application('Elham Installer','1.0.0');
$app->add(new NewInstaller(new Client));
$app->run();
